### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by MarkJiYuan** [wormhole-foundation/wormhole-sdk-ts#568]
After I installed package and start a very simple script, import error suddenly happened, and I don't know how other people can smoothly pass it. I use typescript 4.5.0, ts-node 8.0.0。

This is my code
```
import { wormhole } from "@wormhole-foundation/sdk";
import evm from "@wormhole-foundation/sdk/evm";

async function main() {
  const wh = await wormhole("Testnet", [evm]);
  console.log(wh);

  // console.log(await evm());
}

main();
```

The error is:
```
Failed to load required packages TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at loadProtocols (/Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:88:18)
    at /Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:64:56
    at Array.map (<anonymous>)
    at loadPlatforms (/Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:64:33)
    at async wormhole (/Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:102:14)
    at async main (/Users/jiyuan.zheng/projects/chain-build/packages/test/scripts/wormhole.ts:5:14)
Failed to load required packages TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at loadProtocols (/Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:88:18)
    at /Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:64:56
    at Array.map (<anonymous>)
    at loadPlatforms (/Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:64:33)
    at async wormhole (/Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:102:14)
    at async main (/Users/jiyuan.zheng/projects/chain-build/packages/test/scripts/wormhole.ts:5:14)
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at loadProtocols (/Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:88:18)
    at /Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:64:56
    at Array.map (<anonymous>)
    at loadPlatforms (/Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:64:33)
    at async wormhole (/Users/jiyuan.zheng/projects/chain-build/packages/test/node_modules/@wormhole-foundation/sdk/src/index.ts:102:14)
    at async main (/Users/jiyuan.zheng/projects/chain-build/packages/test/scripts/wormhole.ts:5:14)
```

This is due to evm is an async function, but the result still is a object that have a key `default`. so right know I only have to rewrite node-modules code to pass this, can anyone help me how to fix it?

**Comment by MarkJiYuan** [comment]
I think the problem probably is here: sdk/src/evm.ts, need to export two default:
(await import("./platforms/evm.js")).default.default

**Comment by kupermind** [comment]
@MarkJiYuan what does this line mean? Where is that applied? Could you provide a code example? We are having exactly the same issue with the solana environment.

**Comment by barnjamin** [comment]
1) bump typescript to > 5.0
2) prefer `tsx` to `ts-node`

If those don't fix it please lmk
